# Generated by Django 4.2.5 on 2023-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_laptop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(None, '(Unknown)'), ('CL', 'Culture'), ('SP', 'Sport'), ('PL', 'Politic')], max_length=100),
        ),
    ]
