# Generated by Django 4.2.5 on 2023-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='stock_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='year_of_issue',
            field=models.SmallIntegerField(help_text='year_of issue'),
        ),
    ]
